-- Đã mã hóa BCrypt xuống db trên máy, file sql này chỉ dùng để kiểm tra dữ liệu mẫu và chỉnh sửa nếu cần --

-- Dọn dẹp dữ liệu cũ (nếu có) để tránh lỗi trùng lặp ID khi chạy lại script
TRUNCATE TABLE user_update_requests, transactions, accounts, users RESTART IDENTITY CASCADE;;

-- XOÁ TRIGGER NẾU TỒN TẠI ĐỂ TRÁNH XUNG ĐỘT KHI NẠP DỮ LIỆU MẪU
DROP TRIGGER IF EXISTS trigger_auto_create_account ON users CASCADE;;

-- ====================
-- 1. TẠO CẤU TRÚC BẢNG
-- ====================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    phone_number VARCHAR(20) UNIQUE NOT NULL,
    role VARCHAR(20),
    email VARCHAR(50),
    address VARCHAR(255),
    gender VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 0,
    account_number VARCHAR(20) UNIQUE NOT NULL,
    account_type VARCHAR(50) DEFAULT 'PAYMENT',
    transaction_limit VARCHAR(50) DEFAULT '50M',
    interest_rate DECIMAL(5, 2),
    term_months INT,
    balance DECIMAL(19, 2) DEFAULT 0,
    date_open TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);;

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(50) UNIQUE,
    type VARCHAR(50),
    amount DECIMAL(19, 2),
    description VARCHAR(255),
    transaction_date TIMESTAMP,
    from_account_id BIGINT,
    to_account_id BIGINT,
    CONSTRAINT fk_from_account FOREIGN KEY (from_account_id) REFERENCES accounts(id),
    CONSTRAINT fk_to_account FOREIGN KEY (to_account_id) REFERENCES accounts(id)
);;

CREATE TABLE IF NOT EXISTS user_update_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    new_full_name VARCHAR(255),
    new_phone_number VARCHAR(20),
    new_email VARCHAR(50),
    new_address VARCHAR(255),
    new_gender VARCHAR(20),
    status VARCHAR(20) DEFAULT 'PENDING',
    request_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    detail VARCHAR(500),
    CONSTRAINT fk_request_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);;

-- ========================================================
-- 2. NẠP DỮ LIỆU (100 Users, 200 Accounts, 2 Transactions)
-- ========================================================

-- Nạp 10 User đặc biệt đầu tiên
INSERT INTO users (id, username, password, full_name, phone_number, role, email, address, gender) VALUES
(1, 'user', 'Demo@2026', 'User Default', '0987654321', 'user', 'user1@gmail.com', 'user 1 address', 'Nam'),
(2, 'admin', 'SecureAdmin!2026', 'Quản trị viên', '0912345678', 'admin', 'admin@gmail.com', 'admin address', 'Khác'),
(3, 'mai', 'Mai123@', 'Nguyễn Thị Mai', '0909876543', 'user', 'user3@gmail.com', 'user 3 address', 'Nữ'),
(4, 'bach', 'Bach123@', 'Lê Hoàng Bách', '0938765432', 'user', 'user4@gmail.com', 'user 4 address', 'Nam'),
(5, 'linh', 'Linh321@', 'Nguyễn Ngọc Linh', '0947654321', 'user', 'user5@gmail.com', 'user 5 address', 'Nữ'),
(6, 'han', 'Han456@', 'Đỗ Văn Hấn', '0956789012', 'user', 'user6@gmail.com', 'user 6 address', 'Nam'),
(7, 'nam', 'Nam789@', 'Phạm Văn Nam', '0965432109', 'user', 'user7@gmail.com', 'user 7 address', 'Nam'),
(8, 'hoa', 'Hoa987@', 'Trần Thị Hoa', '0976543210', 'user', 'user8@gmail.com', 'user 8 address', 'Nữ'),
(9, 'tuan', 'Tuan654@', 'Nguyễn Văn Tuấn', '0908070605', 'user', 'user9@gmail.com', 'user 9 address', 'Nam'),
(10, 'hien', 'Hien321@', 'Lê Thị Hiền', '0998765432', 'user', 'user10@gmail.com', 'user 10 address', 'Nữ');;

-- Tự động sinh thêm 90 User (Từ ID 11 đến 100) bằng vòng lặp của PostgreSQL
INSERT INTO users (id, username, password, full_name, phone_number, role, email, address, gender)
SELECT
    s.i,
    'khachhang' || s.i,
    '123456',
    'Khách hàng mẫu số ' || s.i,
    '0980000' || LPAD(s.i::text, 3, '0'),
    'user',
    'user' || s.i || '@gmail.com',
    'user ' || s.i || ' address',
    CASE WHEN s.i % 2 = 0 THEN 'Nữ' ELSE 'Nam' END
FROM generate_series(11, 100) AS s(i);;

-- Nạp 10 Tài khoản thanh toán (PAYMENT) cho 10 User đầu
INSERT INTO accounts (id, version, account_number, account_type, transaction_limit, balance, date_open, user_id) VALUES
(1, 0, '8800000001', 'PAYMENT', '50M', 5000000, '2026-07-17', 1),
(2, 0, '8800000002', 'PAYMENT', '50M', 0, '2026-07-17', 2),
(3, 0, '8800000003', 'PAYMENT', '50M', 25000000, '2026-07-17', 3),
(4, 0, '8800000004', 'PAYMENT', '50M', 340000, '2026-07-17', 4),
(5, 0, '8800000005', 'PAYMENT', '50M', 8000, '2026-07-17', 5),
(6, 0, '8800000006', 'PAYMENT', '50M', 85000000000, '2026-07-17', 6),
(7, 0, '8800000007', 'PAYMENT', '50M', 1234567890, '2026-07-17', 7),
(8, 0, '8800000008', 'PAYMENT', '50M', 5000000, '2026-07-17', 8),
(9, 0, '8800000009', 'PAYMENT', '50M', 7500000, '2026-07-17', 9),
(10, 0, '8800000010', 'PAYMENT', '50M', 12000000, '2026-07-17', 10);;

-- Tự động sinh 90 Tài khoản PAYMENT cho 90 User tiếp theo (Từ ID 11 đến 100)
INSERT INTO accounts (id, version, account_number, account_type, transaction_limit, balance, date_open, user_id)
SELECT
    s.i,
    0, -- Cấp giá trị mặc định cho version
    '8800000' || LPAD(s.i::text, 3, '0'),
    'PAYMENT',
    '50M',
    0,
    '2026-07-17',
    s.i
FROM generate_series(11, 100) AS s(i);;

-- Tự động sinh 100 Tài khoản SAVING cho 100 User (Từ ID 1 đến 100)
INSERT INTO accounts (id, version, account_number, account_type, transaction_limit, interest_rate, term_months, balance, date_open, user_id)
SELECT
    s.i + 100,
    0, -- Cấp giá trị mặc định cho version
    '9900000' || LPAD(s.i::text, 3, '0'),
    'SAVING',
    NULL,
    5.50,
    6,
    CASE WHEN s.i <= 10 THEN 5000000 ELSE 0 END,
    '2026-07-17',
    s.i
FROM generate_series(1, 100) AS s(i);;

-- Nạp Giao dịch mẫu (để DB tự sinh ID tự động)
INSERT INTO transactions (transaction_id, type, amount, description, transaction_date, to_account_id, from_account_id) VALUES
('TXN-20260708-001', 'DEPOSIT', 2000000.00, 'Nạp tiền mặt tại quầy', CURRENT_TIMESTAMP - INTERVAL '3' DAY, 1, NULL),
('TXN-20260708-002', 'WITHDRAW', 500000.00, 'Rút tiền qua ATM', CURRENT_TIMESTAMP - INTERVAL '2' DAY, NULL, 1);;
-- Tự động sinh 500 giao dịch ngẫu nhiên cho các Tài khoản Thanh toán (ID từ 1 đến 100)
INSERT INTO transactions (transaction_id, type, amount, description, transaction_date, from_account_id, to_account_id)
SELECT
    'TXN-' || TO_CHAR(CURRENT_DATE, 'YYYYMMDD') || '-' || LPAD((s.i + 2)::text, 4, '0'),
    CASE
        WHEN s.i % 3 = 0 THEN 'TRANSFER'
        WHEN s.i % 3 = 1 THEN 'DEPOSIT'
        ELSE 'WITHDRAW'
    END,
    (floor(random() * 50) + 5) * 100000, -- Số tiền ngẫu nhiên từ 500.000 đến 5.400.000 VND
    CASE
        WHEN s.i % 3 = 0 THEN 'Chuyển khoản thanh toán ' || s.i
        WHEN s.i % 3 = 1 THEN 'Nạp tiền vào tài khoản ' || s.i
        ELSE 'Rút tiền mặt ' || s.i
    END,
    CURRENT_TIMESTAMP - (random() * 60 || ' days')::interval, -- Thời gian ngẫu nhiên trong 60 ngày đổ lại
    -- Xử lý from_account_id (chỉ áp dụng cho Rút và Chuyển khoản, ID từ 1-100)
    CASE 
        WHEN s.i % 3 = 1 THEN NULL 
        ELSE floor(random() * 100) + 1 
    END,
    -- Xử lý to_account_id (chỉ áp dụng cho Nạp và Chuyển khoản, ID từ 1-100)
    CASE
        WHEN s.i % 3 = 2 THEN NULL
        WHEN s.i % 3 = 0 THEN 
            -- Đảm bảo tài khoản nhận khác tài khoản gửi khi chuyển khoản
            MOD((floor(random() * 100)::int + s.i), 100) + 1
        ELSE floor(random() * 100) + 1
    END
FROM generate_series(1, 500) AS s(i);;

-- ===========================================
-- 3. RESET ĐIỂM BẮT ĐẦU CỦA ID VÀ TẠO TRIGGER
-- ===========================================

ALTER TABLE users ALTER COLUMN id RESTART WITH 101;;
ALTER TABLE accounts ALTER COLUMN id RESTART WITH 201;;
ALTER TABLE transactions ALTER COLUMN id RESTART WITH 503;;
ALTER TABLE user_update_requests ALTER COLUMN id RESTART WITH 1;;

CREATE INDEX IF NOT EXISTS idx_users_phone ON users(phone_number);;
CREATE INDEX IF NOT EXISTS idx_users_fullname ON users(full_name);;